# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowlio < Formula
  desc "Project manager for AI agents: cross-repo issues, and a waker that closes the loop"
  homepage "https://github.com/Coddyum/flowlio-agents"
  version "1.0.6"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.0.6/flowlio_1.0.6_darwin_amd64.tar.gz"
      sha256 "4db30a559717d3e0d3194c506f8c2f177df20d096527bbee386642b91781d13f"

      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.0.6/flowlio_1.0.6_darwin_arm64.tar.gz"
      sha256 "ed85505497a6663715f0d72e32ff2e03a1b346fef97ea2c8c5159c26cc7829ec"

      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.0.6/flowlio_1.0.6_linux_amd64.tar.gz"
      sha256 "226c45101276fe24e0063dee6dc9e44211965cf777ad122959fe89f308e619f4"
      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.0.6/flowlio_1.0.6_linux_arm64.tar.gz"
      sha256 "bfd950c92e79c698393e06de61a49cd5b5ae591c222c6d64975b8ea8f3913ff8"
      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
  end

  def caveats
    <<~EOS
      Self-host runs Postgres 18 in a container flowlio manages — install Docker first, then run:
        flowlio
    EOS
  end

  test do
    assert_match "flowlio", shell_output("#{bin}/flowlio version")
  end
end
