# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowlio < Formula
  desc "Project manager for AI agents: cross-repo issues, and a waker that closes the loop"
  homepage "https://github.com/Coddyum/flowlio-agents"
  version "1.1.1"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.1.1/flowlio_1.1.1_darwin_amd64.tar.gz"
      sha256 "2a5a444a3e108c660969dce2e2d2bd4f6356c2f3c525caa14b3b18815fbb80e3"

      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.1.1/flowlio_1.1.1_darwin_arm64.tar.gz"
      sha256 "6cdf47af5109acdbf6800dcf14dd3e5212286549d538af52112b1b67953ac122"

      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.1.1/flowlio_1.1.1_linux_amd64.tar.gz"
      sha256 "620da405e360ac9b479dc7be4cfff3ede5e787bd323ed92cfdd638a35c03b49d"
      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Coddyum/flowlio-agents/releases/download/v1.1.1/flowlio_1.1.1_linux_arm64.tar.gz"
      sha256 "a4dcaadc9a9555672bc6a43feada5775c51372752be7f5c67e0ecaa645ffdade"
      define_method(:install) do
        bin.install "flowlio"
        bin.install "flowlio-api"
      end
    end
  end

  def caveats
    <<~EOS
      Self-host runs Postgres 18 in a container flowlio manages — install Docker first, then run:
        flowlio
    EOS
  end

  test do
    assert_match "flowlio", shell_output("#{bin}/flowlio version")
  end
end
